name: GitHub Stats Card Generator

on:
  schedule:
    # Runs at 3 AM UTC every day
    - cron: '0 3 * * *'
  workflow_dispatch:

# This permission is essential for the action to commit the generated SVG back to your repo
permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4 
        
      # Step 2: Generate the User Stats Image
      - name: Generate the user stats image
        uses: cicirello/user-statistician@v1
        env:
          # Pass the GitHub Token as an environment variable
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          # Specify the output file name and location
          image-file: 'github-stats.svg' 

          # Include forked repos
          include-forks: 'true'
          
          # Specify which sections to include and their order
          category-order: 'contributions,repositories,languages'
          
          # Use a dark theme
          colors: 'dark-dimmed' 
          
          # Set a custom title for the card
          custom-title: 'My GitHub Activity' 
          
          # Tell the action to commit the new image to the repo
          commit-and-push: 'true'
